### ISSUE TITLE
calc problem

### ISSUE THREAD

**Issue by AntiWarforever** [vanhbakaa/Notpixel-bot#20]
![Capture](https://github.com/user-attachments/assets/4b5bfb2d-8d68-420e-a2fe-4c843db71ed3)
When I activate multi thread & 3X px True
& there are more than 3 accounts
This poses a computational problem
Is there a problem?

**Comment by vanhbakaa** [comment]
no your balance still go up dont worrie about that

**Comment by DrSeaXen** [comment]
@vanhbakaa but 3X point rarely get . not working all time .

**Comment by vanhbakaa** [comment]
> @vanhbakaa but 3X point rarely get . not working all time .

It's better than not thing. It work better if you disable multi thread, chance to get 3x point is 45-50%
