### ISSUE TITLE
x3points problem

### ISSUE THREAD

**Issue by Hamed-Deve** [vanhbakaa/Notpixel-bot#22]
For the 3x points to work correctly, it must be checked before painting whether the target pixel has the correct color or not. For example, if the pixel at coordinates 300,250 is red and we paint it red again, the 3x points will not be applied. Please fix this

**Comment by vanhbakaa** [comment]
I can't if you can fix please do that :)

**Comment by Hamed-Deve** [comment]
I can't 
It would be great if you could do this

**Comment by vanhbakaa** [comment]
i can't because it required some library that doesn't work well on some operating system
