### ISSUE TITLE
Proxy ERROR

### ISSUE THREAD

**Issue by Denys7814** [vanhbakaa/Notpixel-bot#23]
<img width="1470" alt="Знімок екрана 2024-10-05 о 14 32 48" src="https://github.com/user-attachments/assets/9dd531b6-616c-4a60-80ac-ec9ad6aa02a0">

Hello! Please tell me how to fix this error? I use socks5 and http proxy, the error result is the same((

**Comment by vanhbakaa** [comment]
correct format is 
proxy_type:ip:port:user:password

**Comment by Denys7814** [comment]
> correct format is proxy_type:ip:port:user:password

<img width="1148" alt="Знімок екрана 2024-10-05 о 19 47 32" src="https://github.com/user-attachments/assets/fe80c79f-2b15-4a0b-adc6-88e2ee42ebb2">

Thank you for your answer! How can this problem be solved?

**Comment by vanhbakaa** [comment]
open bot/core/tapper.py
 and change function like this:

![image](https://github.com/user-attachments/assets/7efaa8e6-e576-4b5e-8d93-a9458532f883)

**Comment by Denys7814** [comment]
<img width="1148" alt="Знімок екрана 2024-10-05 о 20 10 10" src="https://github.com/user-attachments/assets/f842a441-fa9b-496a-82be-4ab8f19722ac">

Is this how it should be? Is this how the bot works correctly?

**Comment by vanhbakaa** [comment]
yeah

**Comment by Denys7814** [comment]
> yeah

Okay. Thank you very much! Nice.
