### ISSUE TITLE
Multithreading

### ISSUE THREAD

**Issue by Insomnia731** [vanhbakaa/Notpixel-bot#24]
Please explain how to start farming from several accounts at once. I have several sessions in the /session/ folder. But only one .env file. And accordingly where should I add API_ID/API_HASH from the second account?

**Comment by vanhbakaa** [comment]
no u just need 1 api_id/api_hash for all of them

**Comment by Insomnia731** [comment]
> no u just need 1 api_id/api_hash for all of them

But each account has its own api_id/api_hash and its own session. How will account number 2 work with the api_id/api_hash of account number 1? I don't understand this.

**Comment by vanhbakaa** [comment]
> > no u just need 1 api_id/api_hash for all of them
> 
> But each account has its own api_id/api_hash and its own session. How will account number 2 work with the api_id/api_hash of account number 1? I don't understand this.

api_id and api_hash just use to create session for the first time
