### ISSUE TITLE
Time for a break

### ISSUE THREAD

**Issue by Denys7814** [vanhbakaa/Notpixel-bot#26]
<img width="1146" alt="Знімок екрана 2024-10-06 о 11 05 53" src="https://github.com/user-attachments/assets/e170b7cb-08d3-4a73-a663-9e99d659d109">

Hello! Please tell me how to make this time significantly longer? For example, so that it randomly starts in the period of 20-60 minutes.

**Comment by vanhbakaa** [comment]
Update new version to have that option in .env or config.py
