### ISSUE TITLE
kill task

### ISSUE THREAD

**Issue by LoloFrost13** [vanhbakaa/Notpixel-bot#27]

**Comment by LoloFrost13** [comment]
I need a script that runs one software, then closes it after an hour, and launches the next one, it turned out with other software (open and close them, they run just through main.py and somehow everything is more difficult for you), it doesn't work out that way with yours, please help, I'm not good at programming.😔❤️

**Comment by AntiWarforever** [comment]
> I need a script that runs one software, then closes it after an hour, and launches the next one, it turned out with other software (open and close them, they run just through main.py and somehow everything is more difficult for you), it doesn't work out that way with yours, please help, I'm not good at programming.😔❤️

You want run a script(python main.py) then close a after hours open again with rapidly?
