### ISSUE TITLE
Авторизация по query_id

### ISSUE THREAD

**Issue by Danny972** [vanhbakaa/Notpixel-bot#31]
Authorization by query_id stops working after 10-15 minutes. So you load query_id into data.txt, run start.bat, select a bot that works by query_id, and the first cycle is successful. After 15-20 minutes the next cycle begins and query_id no longer works, it writes this error:
![Screenshot_277](https://github.com/user-attachments/assets/4c26337b-1312-4626-8e5e-9a209e6be3ec)

**Comment by kucher93** [comment]
Query ID life 20 min. This is problem in game, not this script

> Authorization by query_id stops working after 10-15 minutes. So you load query_id into data.txt, run start.bat, select a bot that works by query_id, and the first cycle is successful. After 15-20 minutes the next cycle begins and query_id no longer works, it writes this error: ![Screenshot_277](https://private-user-images.githubusercontent.com/184520389/375395529-4c26337b-1312-4626-8e5e-9a209e6be3ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2NjEzOTgsIm5iZiI6MTcyODY2MTA5OCwicGF0aCI6Ii8xODQ1MjAzODkvMzc1Mzk1NTI5LTRjMjYzMzdiLTEzMTItNDYyNi04ZTVlLTlhMjA5ZTZiZTNlYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMVQxNTM4MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNDc2YTRlOGExNWUwZmU1NDE4ZjJkMjhiYzAyNDFkZjRhNTA0ZjgwODYwNDcwOGU2ODAzMzMzMmNmZjc1YWE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ULWvOTrdmAJvQN3uN7854XjStFkuIfw8Afw-yzlaoZU)
