### ISSUE TITLE
X3POINTS

### ISSUE THREAD

**Issue by mMdooD** [vanhbakaa/Notpixel-bot#32]
![C__WINDOWS_system32_cmd exe 10_10_2024 8_32_57 PM](https://github.com/user-attachments/assets/cefd3456-938d-4558-9088-a82b149f661b)

Bro I had a question, why is the robot deducting points from me like this?? like -87 and -99 and -45
and
 the form that the robot chooses, which used to give 3 times the points, has been changed

**Comment by darkPrince74** [comment]
she is a girl
