### ISSUE TITLE
custom coords

### ISSUE THREAD

**Issue by darkPrince74** [vanhbakaa/Notpixel-bot#33]
Hello miss i have no experience in coding, not even basic
so how can i set custom pixel and color for 3x 
help appreciated🙏

plus what is the color of the selected paint in notpixel 
![Screenshot_20241012-031746](https://github.com/user-attachments/assets/1d1142f1-45f8-446c-a9ed-ec1db0e5d0ca)

**Comment by vanhbakaa** [comment]
Okay i will code this feature

**Comment by darkPrince74** [comment]
ok (>‿◠)
