### ISSUE TITLE
X3 points

### ISSUE THREAD

**Issue by generalcyberi** [vanhbakaa/Notpixel-bot#34]
hello my dear friend Thanks for making this script But this script doesn't give triple points, please fix it 🥲🥲

**Comment by vanhbakaa** [comment]
Can you show some screenshot?

**Comment by generalcyberi** [comment]
![Screenshot_2024-10-13-09-54-08-755_ir ilmili telegraph](https://github.com/user-attachments/assets/6b17c531-1b10-4a5d-b185-295e66a40626)


![IMG_20241013_095734](https://github.com/user-attachments/assets/fe5f3c7c-63ee-4069-90d4-cf176e6ca776)

**Comment by vanhbakaa** [comment]
Try new version
