### ISSUE TITLE
1PX

### ISSUE THREAD

**Issue by xHocusPocusx** [vanhbakaa/Notpixel-bot#35]
As per; 

```
UPD: 12.10.2024 (soon)

Now if you draw outside the layout, you only get 1 PX. 

This was done in order to increase interest in creating creativity on canvas, and not just randomly clicking.
```

Can this be fixed?

**Comment by vanhbakaa** [comment]
What is layout ?

**Comment by xNabil** [comment]
> As per;
> 
> ```
> UPD: 12.10.2024 (soon)
> 
> Now if you draw outside the layout, you only get 1 PX. 
> 
> This was done in order to increase interest in creating creativity on canvas, and not just randomly clicking.
> ```
> 
> Can this be fixed?

edit the .env 3x pix=True

worked in my case
![Screenshot_20241012-162839](https://github.com/user-attachments/assets/502b9af9-669a-464e-8b52-1cbb2e2df9be)

**Comment by xHocusPocusx** [comment]
Yes 

> > As per;
> > ```
> > UPD: 12.10.2024 (soon)
> > 
> > Now if you draw outside the layout, you only get 1 PX. 
> > 
> > This was done in order to increase interest in creating creativity on canvas, and not just randomly clicking.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Can this be fixed?
> 
> edit the .env 3x pix=True
> 
> worked in my case ![Screenshot_20241012-162839](https://private-user-images.githubusercontent.com/184257215/375950573-502b9af9-669a-464e-8b52-1cbb2e2df9be.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3Mzg4MTcsIm5iZiI6MTcyODczODUxNywicGF0aCI6Ii8xODQyNTcyMTUvMzc1OTUwNTczLTUwMmI5YWY5LTY2OWEtNDY0ZS04YjUyLTFjYmIyZTJkZjliZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMlQxMzA4MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03Mjk0NzI5MGFlYWIyZDU4NWM2YzJiNTU3Y2VmMDk4ZWU5ZDVhMzA1ZDE4YWU0OGRkNDU3MjQzYTU2ZmIxZTRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.dQufHl4Hc9VJVHB1aCiJaTl71OMBANQxrhEzmmjbYOI)



> > As per;
> > ```
> > UPD: 12.10.2024 (soon)
> > 
> > Now if you draw outside the layout, you only get 1 PX. 
> > 
> > This was done in order to increase interest in creating creativity on canvas, and not just randomly clicking.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Can this be fixed?
> 
> edit the .env 3x pix=True
> 
> worked in my case ![Screenshot_20241012-162839](https://private-user-images.githubusercontent.com/184257215/375950573-502b9af9-669a-464e-8b52-1cbb2e2df9be.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3Mzg4MzQsIm5iZiI6MTcyODczODUzNCwicGF0aCI6Ii8xODQyNTcyMTUvMzc1OTUwNTczLTUwMmI5YWY5LTY2OWEtNDY0ZS04YjUyLTFjYmIyZTJkZjliZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMlQxMzA4NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xODBhMTFkNzA5OWM4NGI0MWRlNDQ2OTllNmNjNGU1OTgzNTVlYjNiOTkxZmY0ZTBmOGE0ZmFlMmRiNDAyNTI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ALkLObDFgVBJ2tEz8uxSm60EXPFAeczmyOQEm_U_I1s)

Yes I have X3POINTS=True. But I am getting only 1PX, instead of 4PX when I am paintaing.

**Comment by xNabil** [comment]
give me a ss of your .env file ,,let me see

**Comment by xHocusPocusx** [comment]
![image](https://github.com/user-attachments/assets/62c16445-98c3-473f-b257-b75b67b0e2fa)
I have Paint Reward upgraded to max.

**Comment by xNabil** [comment]
my `.env`
![Screenshot_20241012-192237](https://github.com/user-attachments/assets/b7dae22d-cd63-4185-8e25-7b061fd1eb11)
my script is working fine 🐸 
![Screenshot_20241012-192150](https://github.com/user-attachments/assets/6452e1a5-e86e-4270-8157-afd71127095d)

**Comment by xHocusPocusx** [comment]
> my `.env` ![Screenshot_20241012-192237](https://private-user-images.githubusercontent.com/184257215/375960484-b7dae22d-cd63-4185-8e25-7b061fd1eb11.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3NDE3MDQsIm5iZiI6MTcyODc0MTQwNCwicGF0aCI6Ii8xODQyNTcyMTUvMzc1OTYwNDg0LWI3ZGFlMjJkLWNkNjMtNDE4NS04ZTI1LTdiMDYxZmQxZWIxMS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMlQxMzU2NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YjFlZDI2YTgxOTE3YjZiOTk5ZjdlNDBlYTVhNjIxY2E4NTQ3YTc0ODlkYTc5NWZhMGE4OWRiNTdkOTYxMjVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.umCJXF4DnpHSfYuRmIWO4bR3gAeO-pEjHPXtgvXNvtQ) my script is working fine 🐸 ![Screenshot_20241012-192150](https://private-user-images.githubusercontent.com/184257215/375960528-6452e1a5-e86e-4270-8157-afd71127095d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3NDE3MDQsIm5iZiI6MTcyODc0MTQwNCwicGF0aCI6Ii8xODQyNTcyMTUvMzc1OTYwNTI4LTY0NTJlMWE1LWU4NmUtNDI3MC04MTU3LWFmZDcxMTI3MDk1ZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMlQxMzU2NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYzc1YWE2MTZiZDhhMGU2YjU4M2M2MzRiODc0N2NmMDhmMTExMzA4NGZjYzU0MjdhNGFhYjE2MjYwZmRjZWFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.F2jeFSysg6mxD1RjMvfDXAqOH0BzRPWLSVq7yf7ZyFQ)

Well! you missed the point! 

Look, you are earning 1PX, whether it should be 3/4PX according to your level.
