### ISSUE TITLE
how to .env for Sleep?

### ISSUE THREAD

**Issue by xNabil** [vanhbakaa/Notpixel-bot#37]
how to edit `.env` for Sleep time & sleep between each round ?
![Screenshot_20241012-162839](https://github.com/user-attachments/assets/30531782-123f-41e9-9ee8-856a83d87997)

I tried but it shows error 
![Screenshot_20241012-162420](https://github.com/user-attachments/assets/c2e7513f-61f5-41dd-9698-f93620762f43)

 can u give me a example?

**Comment by vanhbakaa** [comment]
[1000, 1500] it's in second

**Comment by xNabil** [comment]
> [1000, 1500] it's in second

oh i missed the space that's why it wasn't working ,,
thanks 💝
luv you & your works 💝👽
