### ISSUE TITLE
telethon

### ISSUE THREAD

**Issue by toastyy00** [vanhbakaa/Notpixel-bot#4]
it could be cool if you add telethon to support this script

**Comment by Pawansingh333** [comment]
telethon will ban your acconts, pyrogram is safe than telethon

**Comment by toastyy00** [comment]
ohh, i got instant ban when using pyrogram

**Comment by vanhbakaa** [comment]
> ohh, i got instant ban when using pyrogram. when the telethon is safe

They have the same risk. But if your telegram is new you shouldn't use bot with session. So that why i added query option
