### ISSUE TITLE
Again the print 0 ☹️☹️

### ISSUE THREAD

**Issue by savan878** [vanhbakaa/Notpixel-bot#48]

**Comment by savan878** [comment]
![Uploading Screenshot_2024-10-15-10-35-58-590_com.termux.jpg…]()

**Comment by mahdi429** [comment]
I have the same problem

**Comment by prognt** [comment]
same

**Comment by izhbec** [comment]
same

**Comment by sanioooook** [comment]
I think they introduced protection against bots in this way. if you redraw a black pixel with black, for example, you get 0, otherwise everything is fine
