### ISSUE TITLE
Getting This king of error failed to repaint

### ISSUE THREAD

**Issue by Safin007** [vanhbakaa/Notpixel-bot#50]
is there any problem with is king of error?

![IMG_20241016_101352](https://github.com/user-attachments/assets/98c1fda8-4c6d-473a-94b0-4804f1f11a4a)

**Comment by ryandhikacc** [comment]
wait few mins till your energy recharge then re-run the scripts, i have this problem and now ONLY this scripts in github that works perfectly with minimum 0 points. Thanks @vanhbakaa ! (i tried other scripts, have massive 0 points per run) 
![image](https://github.com/user-attachments/assets/3f052034-1405-4176-baf4-aaacc4133cf1)
![image](https://github.com/user-attachments/assets/2dbd843c-b6a7-41d2-bfa7-1b0eb123a05a)

**Comment by vanhbakaa** [comment]
> is there any problem with is king of error?
> 
> ![IMG_20241016_101352](https://private-user-images.githubusercontent.com/44508137/376886315-98c1fda8-4c6d-473a-94b0-4804f1f11a4a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwODAyMzMsIm5iZiI6MTcyOTA3OTkzMywicGF0aCI6Ii80NDUwODEzNy8zNzY4ODYzMTUtOThjMWZkYTgtNGM2ZC00NzNhLTk0YjAtNDgwNGYxZjExYTRhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDExNTg1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkMjBiOTBjMGYzNDE3MDk5ZjEyY2YzNzE4N2Y4NGUzNTFmMjU5MzE4MGIwODE3YWEwMWU3MzljMmRiNjg5ZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.swiwTuwY1o-Ger2I8ZO3ygWRwbjVTx5RlIb4z568tdM)

I have updated error handle in new version
