### ISSUE TITLE
Question about painting according to template

### ISSUE THREAD

**Issue by sanioooook** [vanhbakaa/Notpixel-bot#54]
Does the bot just put a pixel in a random place in the template, or does it get different pixels and repaint them in the right color?

**Comment by sanioooook** [comment]
![image](https://github.com/user-attachments/assets/f65cf3a0-db43-4222-b4c8-939150b9f08b)
then why do I keep getting 0? sometimes -1 (but it doesn't change the balance)

**Comment by vanhbakaa** [comment]
> ![image](https://private-user-images.githubusercontent.com/33792718/377138675-f65cf3a0-db43-4222-b4c8-939150b9f08b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwOTU4MTYsIm5iZiI6MTcyOTA5NTUxNiwicGF0aCI6Ii8zMzc5MjcxOC8zNzcxMzg2NzUtZjY1Y2YzYTAtZGI0My00MjIyLWI0YzgtOTM5MTUwYjlmMDhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDE2MTgzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1OTdmOGM0OTc5OTdmZGZhYjk4ZGZhZjBlZDY4ZDI0MWUxNTVjOWFjOGE1NjJhZGIzZDU3OTQ5NDI3OTI2N2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Rc4lEtCY61OZ-DcyHonR22HB0tBM2KuT4-bcAi8EX4E) then why do I keep getting 0? sometimes -1 (but it doesn't change the balance)

It pick a random cordinate in the template and repaint correct color of that pixel

**Comment by sanioooook** [comment]
I understood, it's about the chosen template. There are too many people drawing it

**Comment by YangN1225** [comment]
how can i do

**Comment by YangN1225** [comment]
> 我明白了，这是关于所选模板的问题。画它的人太多了

how can i do
