### ISSUE TITLE
Server unreachable

### ISSUE THREAD

**Issue by miliardov** [vanhbakaa/Notpixel-bot#65]
![image](https://github.com/user-attachments/assets/6ada6c08-70c3-44d2-887b-8251a1e4fbe5)

After the update, the error is now Server unreachable, retrying in 30 seconds.
The script was working before. What's the problem?
This triggers an exception from the image_checker file in the reachable function. What does that mean?

**Comment by vanhbakaa** [comment]
Try new version

**Comment by miliardov** [comment]
> Try new version

![image](https://github.com/user-attachments/assets/2f1f3dee-a002-4f52-a48d-65442809826c)

The error remains

**Comment by miliardov** [comment]
> Try new version

![image](https://github.com/user-attachments/assets/27996aba-5864-4e86-ae6f-400228da50b4)

These changes didn't help either

**Comment by ryandhikacc** [comment]
server is fine for me, but the points earned is only 11.5 while you paint manually you got 12. @vanhbakaa 
![image](https://github.com/user-attachments/assets/257d0db7-5af3-4d18-be7a-a7ea7e66ee6e)

**Comment by alimurar** [comment]
Server is not working for me too..

**Comment by alimurar** [comment]
did you change anything? @ryandhikacc
