### ISSUE TITLE
Error in network 
Retrying in 1802s

### ISSUE THREAD

**Issue by SatyamPote** [vanhbakaa/Notpixel-bot#73]
![Screenshot_2024-10-22-23-05-08-86_84d3000e3f4017145260f7618db1d683.jpg](https://github.com/user-attachments/assets/f46b2dd5-b8c3-4333-ba5f-1f1b8ebddfc7)

**Comment by vanhbakaa** [comment]
Look at thier map its error from thier server

**Comment by SatyamPote** [comment]
How should I fix it I their any way to fix this permanently ✅🗿

**Comment by SatyamPote** [comment]
> Look at thier map its error from thier server

![Screenshot_2024-10-23-22-15-20-24_84d3000e3f4017145260f7618db1d683.jpg](https://github.com/user-attachments/assets/cf381d08-8cc4-4f12-ac34-0c4c009b74f4)
Sorry to say but this not gona work I am only depend on you script ( REPO ) But look like this not gona work 
I don't have any network error I have a 5G wifi + 5G 📱
