### ISSUE TITLE
Server Unreachable

### ISSUE THREAD

**Issue by alimurar** [vanhbakaa/Notpixel-bot#74]
<img width="774" alt="Screenshot 2024-10-23 at 16 30 57" src="https://github.com/user-attachments/assets/c566c09a-eaba-4354-8d0d-095f6dcf7895">

**Comment by AxeRionx** [comment]
> still facing the same issue

Notpixel change api endpoint

**Comment by SatyamPote** [comment]
You can fix the Ishu , just go to proxy.txt and remove all promise with help of this commands

nano proxy.txt
The remove all proxis 
Then commands : 1) ctrl + o      2) ctrl + x 
This gona save the file and then run it
It will definitely works ✅🗿
