### ISSUE TITLE
multi-thread --> 400 Client Error

### ISSUE THREAD

**Issue by pixelincorp** [vanhbakaa/Notpixel-bot#82]
"multi-thread" causes the error "Failed to paint due to network error: 400 Client Error: Bad Request for url: https://notpx.app/api/v1/repaint/start"
if it disabled, then after any drawing error the script continues, like this:
![image](https://github.com/user-attachments/assets/ea8df7bd-91aa-4cff-9f6d-71e2c338484a)

**Comment by vanhbakaa** [comment]
you should turn it off if you don't have proxies
