### ISSUE TITLE
Exceeded 30 redirects.

### ISSUE THREAD

**Issue by RedWilly** [vanhbakaa/Notpixel-bot#88]
|NOTPX    |   File "/root/Notpixel-bot/venv/lib/python3.11/site-packages/cloudscraper/__init__.py", line 192, in perform_request
5|NOTPX    |     return super(CloudScraper, self).request(method, url, *args, **kwargs)
5|NOTPX    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
5|NOTPX    |   File "/root/Notpixel-bot/venv/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
5|NOTPX    |     resp = self.send(prep, **send_kwargs)
5|NOTPX    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
5|NOTPX    |   File "/root/Notpixel-bot/venv/lib/python3.11/site-packages/requests/sessions.py", line 724, in send
5|NOTPX    |     history = [resp for resp in gen]
5|NOTPX    |               ^^^^^^^^^^^^^^^^^^^^^^
5|NOTPX    |   File "/root/Notpixel-bot/venv/lib/python3.11/site-packages/requests/sessions.py", line 724, in <listcomp>
5|NOTPX    |     history = [resp for resp in gen]
5|NOTPX    |               ^^^^^^^^^^^^^^^^^^^^^^
5|NOTPX    |   File "/root/Notpixel-bot/venv/lib/python3.11/site-packages/requests/sessions.py", line 191, in resolve_redirects
5|NOTPX    |     raise TooManyRedirects(
5|NOTPX    | requests.exceptions.TooManyRedirects: Exceeded 30 redirects.

**Comment by 5olnce** [comment]
same
