### ISSUE TITLE
No module name better proxy 

### ISSUE THREAD

**Issue by SatyamPote** [vanhbakaa/Notpixel-bot#98]
[*] https://mirrors.middlendian.com/termux/termux-main: ok
Hit:1 https://turdl.kcubeterm.com tur-packages InRelease
Hit:2 https://mirrors.middlendian.com/termux/termux-main stable InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
No mirror or mirror group selected. You might want to select one by running 'termux-change-repo'
Checking availability of current mirror:
[*] https://mirrors.middlendian.com/termux/termux-main: ok
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
python is already the newest version (3.12.7-1).
rust is already the newest version (1.82.0).
git is already the newest version (2.47.0).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
fatal: destination path 'Notpixel-bot' already exists and is not an empty directory.
Collecting aiocfscrape==1.0.0 (from -r requirements.txt (line 1))
  Using cached aiocfscrape-1.0.0-py3-none-any.whl
Collecting aiohttp==3.9.3 (from -r requirements.txt (line 2))
  Using cached aiohttp-3.9.3-cp312-cp312-linux_aarch64.whl
Collecting aiohttp-proxy==0.1.2 (from -r requirements.txt (line 3))
  Using cached aiohttp_proxy-0.1.2-py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: aiosignal==1.3.1 in /data/data/com.termux/files/usr/lib/python3.12/site-packages (from -r requirements.txt (line 4)) (1.3.1)
Collecting annotated-types==0.6.0 (from -r requirements.txt (line 5))
  Using cached annotated_types-0.6.0-py3-none-any.whl.metadata (12 kB)
Collecting async-timeout==4.0.3 (from -r requirements.txt (line 6))
  Using cached async_timeout-4.0.3-py3-none-any.whl.metadata (4.2 kB)
Collecting attrs==23.2.0 (from -r requirements.txt (line 7))
  Using cached attrs-23.2.0-py3-none-any.whl.metadata (9.5 kB)
Collecting beautifulsoup4==4.12.3 (from -r requirements.txt (line 8))
  Using cached beautifulsoup4-4.12.3-py3-none-any.whl.metadata (3.8 kB)
Collecting better-proxy==1.1.5 (from -r requirements.txt (line 9))
  Using cached better_proxy-1.1.5-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: certifi==2024.8.30 in /data/data/com.termux/files/usr/lib/python3.12/site-packages (from -r requirements.txt (line 10)) (2024.8.30)
Collecting charset-normalizer==3.3.2 (from -r requirements.txt (line 11))
  Using cached charset_normalizer-3.3.2-py3-none-any.whl.metadata (33 kB)
Collecting cloudscraper==1.2.71 (from -r requirements.txt (line 12))
  Using cached cloudscraper-1.2.71-py2.py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: colorama==0.4.6 in /data/data/com.termux/files/usr/lib/python3.12/site-packages (from -r requirements.txt (line 13)) (0.4.6)
Collecting DateTime==5.5 (from -r requirements.txt (line 14))
  Using cached DateTime-5.5-py3-none-any.whl.metadata (33 kB)
Collecting Faker==29.0.0 (from -r requirements.txt (line 15))
  Using cached Faker-29.0.0-py3-none-any.whl.metadata (15 kB)
Collecting frozenlist==1.4.1 (from -r requirements.txt (line 16))
  Using cached frozenlist-1.4.1-py3-none-any.whl.metadata (12 kB)
Collecting idna==3.6 (from -r requirements.txt (line 17))
  Using cached idna-3.6-py3-none-any.whl.metadata (9.9 kB)
Collecting Js2Py==0.74 (from -r requirements.txt (line 18))
  Using cached Js2Py-0.74-py3-none-any.whl.metadata (868 bytes)
Requirement already satisfied: loguru==0.7.2 in /data/data/com.termux/files/usr/lib/python3.12/site-packages (from -r requirements.txt (line 19)) (0.7.2)
Collecting multidict==6.0.5 (from -r requirements.txt (line 20))
  Using cached multidict-6.0.5-py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: pyaes==1.6.1 in /data/data/com.termux/files/usr/lib/python3.12/site-packages (from -r requirements.txt (line 21)) (1.6.1)
Collecting pycryptodome==3.20.0 (from -r requirements.txt (line 22))
  Using cached pycryptodome-3.20.0-cp35-abi3-linux_aarch64.whl
Collecting pydantic==2.6.4 (from -r requirements.txt (line 23))
  Using cached pydantic-2.6.4-py3-none-any.whl.metadata (85 kB)
Collecting pydantic-settings==2.2.1 (from -r requirements.txt (line 24))
  Using cached pydantic_settings-2.2.1-py3-none-any.whl.metadata (3.1 kB)
Collecting pydantic_core==2.16.3 (from -r requirements.txt (line 25))
  Using cached pydantic_core-2.16.3.tar.gz (368 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pyjsparser==2.7.1 (from -r requirements.txt (line 26))
  Using cached pyjsparser-2.7.1-py3-none-any.whl
Collecting pyparsing==3.1.4 (from -r requirements.txt (line 27))
  Using cached pyparsing-3.1.4-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: Pyrogram==2.0.106 in /data/data/com.termux/files/usr/lib/python3.12/site-packages (from -r requirements.txt (line 28)) (2.0.106)
Requirement already satisfied: PySocks==1.7.1 in /data/data/com.termux/files/usr/lib/python3.12/site-packages (from -r requirements.txt (line 29)) (1.7.1)
Collecting python-dateutil==2.9.0.post0 (from -r requirements.txt (line 30))
  Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting python-dotenv==1.0.1 (from -r requirements.txt (line 31))
  Using cached python_dotenv-1.0.1-py3-none-any.whl.metadata (23 kB)
Collecting pytz==2024.1 (from -r requirements.txt (line 32))
  Using cached pytz-2024.1-py2.py3-none-any.whl.metadata (22 kB)
Collecting requests==2.32.3 (from -r requirements.txt (line 33))
  Using cached requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Collecting requests-toolbelt==1.0.0 (from -r requirements.txt (line 34))
  Using cached requests_toolbelt-1.0.0-py2.py3-none-any.whl.metadata (14 kB)
Collecting six==1.16.0 (from -r requirements.txt (line 35))
  Using cached six-1.16.0-py2.py3-none-any.whl.metadata (1.8 kB)
Collecting soupsieve==2.5 (from -r requirements.txt (line 36))
  Using cached soupsieve-2.5-py3-none-any.whl.metadata (4.7 kB)
Collecting TgCrypto==1.2.5 (from -r requirements.txt (line 37))
  Using cached TgCrypto-1.2.5-cp312-cp312-linux_aarch64.whl
Collecting typing_extensions==4.11.0 (from -r requirements.txt (line 38))
  Using cached typing_extensions-4.11.0-py3-none-any.whl.metadata (3.0 kB)
Collecting tzdata==2024.1 (from -r requirements.txt (line 39))
  Using cached tzdata-2024.1-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting tzlocal==5.2 (from -r requirements.txt (line 40))
  Using cached tzlocal-5.2-py3-none-any.whl.metadata (7.8 kB)
Collecting urllib3==2.2.2 (from -r requirements.txt (line 41))
  Using cached urllib3-2.2.2-py3-none-any.whl.metadata (6.4 kB)
Collecting websockets==12.0 (from -r requirements.txt (line 42))
  Using cached websockets-12.0-py3-none-any.whl.metadata (6.6 kB)
Collecting win32-setctime==1.1.0 (from -r requirements.txt (line 43))
  Using cached win32_setctime-1.1.0-py3-none-any.whl.metadata (2.3 kB)
Collecting yarl==1.9.4 (from -r requirements.txt (line 44))
  Using cached yarl-1.9.4-py3-none-any.whl.metadata (31 kB)
Collecting zope.interface==6.4.post2 (from -r requirements.txt (line 45))
  Using cached zope.interface-6.4.post2-cp312-cp312-linux_aarch64.whl
Collecting pillow==10.4.0 (from -r requirements.txt (line 46))
  Using cached pillow-10.4.0-cp312-cp312-linux_aarch64.whl
Collecting setuptools (from zope.interface==6.4.post2->-r requirements.txt (line 45))
  Using cached setuptools-75.3.0-py3-none-any.whl.metadata (6.9 kB)
Using cached aiohttp_proxy-0.1.2-py3-none-any.whl (12 kB)
Using cached annotated_types-0.6.0-py3-none-any.whl (12 kB)
Using cached async_timeout-4.0.3-py3-none-any.whl (5.7 kB)
Using cached attrs-23.2.0-py3-none-any.whl (60 kB)
Using cached beautifulsoup4-4.12.3-py3-none-any.whl (147 kB)
Using cached better_proxy-1.1.5-py3-none-any.whl (3.2 kB)
Using cached charset_normalizer-3.3.2-py3-none-any.whl (48 kB)
Using cached cloudscraper-1.2.71-py2.py3-none-any.whl (99 kB)
Using cached DateTime-5.5-py3-none-any.whl (52 kB)
Using cached Faker-29.0.0-py3-none-any.whl (1.8 MB)
Using cached frozenlist-1.4.1-py3-none-any.whl (11 kB)
Using cached idna-3.6-py3-none-any.whl (61 kB)
Using cached Js2Py-0.74-py3-none-any.whl (1.0 MB)
Using cached multidict-6.0.5-py3-none-any.whl (9.7 kB)
Using cached pydantic-2.6.4-py3-none-any.whl (394 kB)
Using cached pydantic_settings-2.2.1-py3-none-any.whl (13 kB)
Using cached pyparsing-3.1.4-py3-none-any.whl (104 kB)
Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
Using cached python_dotenv-1.0.1-py3-none-any.whl (19 kB)
Using cached pytz-2024.1-py2.py3-none-any.whl (505 kB)
Using cached requests-2.32.3-py3-none-any.whl (64 kB)
Using cached requests_toolbelt-1.0.0-py2.py3-none-any.whl (54 kB)
Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Using cached soupsieve-2.5-py3-none-any.whl (36 kB)
Using cached typing_extensions-4.11.0-py3-none-any.whl (34 kB)
Using cached tzdata-2024.1-py2.py3-none-any.whl (345 kB)
Using cached tzlocal-5.2-py3-none-any.whl (17 kB)
Using cached urllib3-2.2.2-py3-none-any.whl (121 kB)
Using cached websockets-12.0-py3-none-any.whl (118 kB)
Using cached win32_setctime-1.1.0-py3-none-any.whl (3.6 kB)
Using cached yarl-1.9.4-py3-none-any.whl (31 kB)
Using cached setuptools-75.3.0-py3-none-any.whl (1.3 MB)
Building wheels for collected packages: pydantic_core
  Building wheel for pydantic_core (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for pydantic_core (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [111 lines of output]
      Running `maturin pep517 build-wheel -i /data/data/com.termux/files/usr/bin/python3.12 --compatibility off`
      📦 Including license file "/data/data/com.termux/files/usr/tmp/pip-install-_b8gx62z/pydantic-core_99ab02bd0f3a40fbbd3476971d39042a/LICENSE"
      🍹 Building a mixed python/rust project
      🔗 Found pyo3 bindings
      🐍 Found CPython 3.12 at /data/data/com.termux/files/usr/bin/python3.12
      📡 Using build options features, bindings from pyproject.toml
         Compiling autocfg v1.1.0
         Compiling proc-macro2 v1.0.76
         Compiling target-lexicon v0.12.9
         Compiling unicode-ident v1.0.10
         Compiling python3-dll-a v0.2.9
         Compiling libc v0.2.147
         Compiling once_cell v1.18.0
         Compiling cfg-if v1.0.0
         Compiling version_check v0.9.4
         Compiling heck v0.4.1
         Compiling static_assertions v1.1.0
         Compiling lexical-util v0.8.5
         Compiling parking_lot_core v0.9.8
         Compiling rustversion v1.0.13
         Compiling num-traits v0.2.16
         Compiling ahash v0.8.7
         Compiling num-integer v0.1.45
         Compiling lock_api v0.4.10
         Compiling zerocopy v0.7.32
         Compiling num-bigint v0.4.4
         Compiling memoffset v0.9.0
         Compiling pyo3-build-config v0.20.2
         Compiling allocator-api2 v0.2.16
         Compiling quote v1.0.35
         Compiling syn v2.0.48
         Compiling getrandom v0.2.10
         Compiling tinyvec_macros v0.1.1
         Compiling scopeguard v1.1.0
         Compiling smallvec v1.11.2
         Compiling tinyvec v1.6.0
         Compiling hashbrown v0.14.3
         Compiling lexical-parse-integer v0.8.6
         Compiling lexical-write-integer v0.8.5
         Compiling serde v1.0.195
         Compiling memchr v2.6.3
         Compiling unicode-normalization v0.1.22
         Compiling lexical-write-float v0.8.5
         Compiling lexical-parse-float v0.8.5
         Compiling pyo3-ffi v0.20.2
         Compiling pyo3 v0.20.2
         Compiling aho-corasick v1.0.2
         Compiling parking_lot v0.12.1
         Compiling regex-syntax v0.8.2
         Compiling percent-encoding v2.3.1
         Compiling equivalent v1.0.1
         Compiling serde_json v1.0.109
         Compiling unicode-bidi v0.3.13
         Compiling indoc v2.0.4
         Compiling unindent v0.2.3
         Compiling form_urlencoded v1.2.1
         Compiling idna v0.5.0
         Compiling indexmap v2.0.0
         Compiling lexical-core v0.8.5
         Compiling pydantic-core v2.16.3 (/data/data/com.termux/files/usr/tmp/pip-install-_b8gx62z/pydantic-core_99ab02bd0f3a40fbbd3476971d39042a)
         Compiling ryu v1.0.14
         Compiling itoa v1.0.8
         Compiling url v2.5.0
      error: failed to run custom build command for `pydantic-core v2.16.3 (/data/data/com.termux/files/usr/tmp/pip-install-_b8gx62z/pydantic-core_99ab02bd0f3a40fbbd3476971d39042a)`

      Caused by:
        process didn't exit successfully: `/data/data/com.termux/files/usr/tmp/pip-install-_b8gx62z/pydantic-core_99ab02bd0f3a40fbbd3476971d39042a/target/release/build/pydantic-core-3655345edbe7d3ca/build-script-build` (exit status: 101)
        --- stdout
        cargo:rustc-cfg=Py_3_6
        cargo:rustc-cfg=Py_3_7
        cargo:rustc-cfg=Py_3_8
        cargo:rustc-cfg=Py_3_9
        cargo:rustc-cfg=Py_3_10
        cargo:rustc-cfg=Py_3_11
        cargo:rustc-cfg=Py_3_12
        cargo:rerun-if-changed=python/pydantic_core/core_schema.py
        cargo:rerun-if-changed=generate_self_schema.py

        --- stderr
        Traceback (most recent call last):
          File "/data/data/com.termux/files/usr/tmp/pip-install-_b8gx62z/pydantic-core_99ab02bd0f3a40fbbd3476971d39042a/generate_self_schema.py", line 192, in eval_forward_ref
            return type_._evaluate(core_schema.__dict__, None, set())
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'

        During handling of the above exception, another exception occurred:

        Traceback (most recent call last):
          File "/data/data/com.termux/files/usr/tmp/pip-install-_b8gx62z/pydantic-core_99ab02bd0f3a40fbbd3476971d39042a/generate_self_schema.py", line 240, in <module>
            main()
          File "/data/data/com.termux/files/usr/tmp/pip-install-_b8gx62z/pydantic-core_99ab02bd0f3a40fbbd3476971d39042a/generate_self_schema.py", line 210, in main
            value = get_schema(s, definitions)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "/data/data/com.termux/files/usr/tmp/pip-install-_b8gx62z/pydantic-core_99ab02bd0f3a40fbbd3476971d39042a/generate_self_schema.py", line 54, in get_schema
            return type_dict_schema(obj, definitions)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "/data/data/com.termux/files/usr/tmp/pip-install-_b8gx62z/pydantic-core_99ab02bd0f3a40fbbd3476971d39042a/generate_self_schema.py", line 152, in type_dict_schema
            field_type = eval_forward_ref(field_type)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          File "/data/data/com.termux/files/usr/tmp/pip-install-_b8gx62z/pydantic-core_99ab02bd0f3a40fbbd3476971d39042a/generate_self_schema.py", line 195, in eval_forward_ref
            return type_._evaluate(core_schema.__dict__, None)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'
        thread 'main' panicked at build.rs:29:9:
        generate_self_schema.py failed with exit status: 1
        note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
      warning: build failed, waiting for other jobs to finish...
      💥 maturin failed
        Caused by: Failed to build a native library through cargo
        Caused by: Cargo build finished with "exit status: 101": `env -u CARGO PYO3_ENVIRONMENT_SIGNATURE="cpython-3.12-64bit" PYO3_PYTHON="/data/data/com.termux/files/usr/bin/python3.12" PYTHON_SYS_EXECUTABLE="/data/data/com.termux/files/usr/bin/python3.12" "cargo" "rustc" "--features" "pyo3/extension-module" "--message-format" "json-render-diagnostics" "--manifest-path" "/data/data/com.termux/files/usr/tmp/pip-install-_b8gx62z/pydantic-core_99ab02bd0f3a40fbbd3476971d39042a/Cargo.toml" "--release" "--lib" "--crate-type" "cdylib"`
      Error: command ['maturin', 'pep517', 'build-wheel', '-i', '/data/data/com.termux/files/usr/bin/python3.12', '--compatibility', 'off'] returned non-zero exit status 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pydantic_core
Failed to build pydantic_core
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (pydantic_core)
TgCrypto is missing! Pyrogram will work the same, but at a much slower speed. More info: https://docs.pyrogram.org/topics/speedups
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/Notpixel-bot/main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "/data/data/com.termux/files/home/Notpixel-bot/bot/utils/__init__.py", line 2, in <module>
    from . import launcher
  File "/data/data/com.termux/files/home/Notpixel-bot/bot/utils/launcher.py", line 9, in <module>
    from better_proxy import Proxy
ModuleNotFoundError: No module named 'better_proxy'

**Comment by vanhbakaa** [comment]
Join my channel for full setup

**Comment by SatyamPote** [comment]
Please discard changes to pull the old script 
And use it as a interior file in device 
Till you get a new server
